### ISSUE TITLE
Pygenx for Julia 1.7

### ISSUE THREAD

**Issue by iAnkiit** [danielolsen/pygenx#11]
Can we have pygenx for Julia 1.7 or more? 
I am unable to run  it actually.
Could you please guide the steps ?

**Comment by danielolsen** [comment]
Hello @iAnkiit,

Adding compatibility for more recent versions of Julia is definitely on my to-do list. When I first created this repo, GenX was limited to using Julia 1.3, but it now lists its compatibility as with Julia 1.5 and 1.6. I'm not sure whether it works with Julia 1.7 yet, but if not, then this python interface will not work either.

With the version of GenX that this interface was designed for (the `old_version` branch in their repo) and pygenx properly installed, you should be able to launch models using the syntax shown at https://github.com/danielolsen/pygenx#using-pygenx-to-launch-genx-models. If not, could you please add documentation of what you tried (including version information for python, Julia, GenX, and pygenx) so that I can try to reproduce the error?

**Comment by iAnkiit** [comment]
Sure @danielolsen , I would share a document with steps I followed and difficulties I faced. 
FYI, I am able to run GenX on v1.7.2.

**Comment by iAnkiit** [comment]
I am unable to install pygenx with "pip install pygenx".
![image](https://user-images.githubusercontent.com/77894719/157422006-2d47cdfc-58ea-4514-a1f0-36a072f402e1.png)

**Comment by danielolsen** [comment]
This package is not registered on pypi, but another older package is registered under the same name: https://pypi.org/project/pygenx/

This package can be installed by running `pip install .` from the root of the repository.

**Comment by iAnkiit** [comment]
Still unable use pygenx. Tried different ways to install pygenx library in python.

**Comment by danielolsen** [comment]
The package has been tested successfully using the language and package versions and process listed in the documentation. I'm unable to help you without more information on your local environment, the exact steps you're trying, and the errors you're receiving.
